### ISSUE TITLE
Better to explicitly state `stepId` must be mandatory within a workflow

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#128]
From @handrews feedback [review](https://github.com/OAI/sig-workflows/issues/49#issuecomment-1836661780).

regarding `stepId`, the spec state:
> Unique string to represent the step. The id SHOULD be unique amongst all steps described in the workflow. The stepId value is case-sensitive. Tools and libraries MAY use the stepId to uniquely identify a workflow step, therefore, it is RECOMMENDED to follow common programming naming conventions. SHOULD conform to the regular expression [A-Za-z0-9_-]+.

Is there any guidance that can be given around what happens when these SHOULDs are disregarded? Is arbitrary behavior allowed (that is what the current wording implies)? Is there any expectation about raising an error on duplicates? Is the SHOULD-ness of the regular expression to allow for names correlating to programming languages with different naming requirements?

A particularly tricky case is when the description is made of multiple documents, a stepId is referenced in a non-entry document, and both that non-entry document and the entry document contain a step with that stepId. This can get even more complex if the stepId also appears in additional documents within the description.

**Comment by frankkilcommins** [comment]
@handrews I agree it better to explicitly enforce uniqueness of a `stepId` within a workflow, I'll change to the key word to a "MUST"

**Comment by frankkilcommins** [comment]
> A particularly tricky case is when the description is made of multiple documents, a stepId is referenced in a non-entry document, and both that non-entry document and the entry document contain a step with that stepId. This can get even more complex if the stepId also appears in additional documents within the description.

@handrews this should not be an issue as to reference a step in non-entry workflow requires you to declare the workflow within the `sourceDescriptions` which then act like a namespace allowing you to reference a particular stepId therein.

**Comment by handrews** [comment]
@frankkilcommins ah, yes, the namespacing part does prevent that problem (the lack of it is what causes the additional problems with OAS's `operationId` implicit referencing).

**Comment by handrews** [comment]
@frankkilcommins I'm guessing you plan to leave the regexp SHOULD/RECOMMENDED as-is, which (looking at this again) I think is fine as it is clear that the consequence of disregarding them is simply that tools will not be able to generate code with those names.

While it's perhaps not necessary for 1.0, you might want to think about how compliance would be assessed here in future test suites or certification programs.  But that's a larger topic and applies to all SHOULDs/RECOMMENDEDs in a spec.  We need to think about that for OAS as well, so maybe that can be an OAI-wide conversation.
