### ISSUE TITLE
Enforce Reference Object value overrides to avoid possible disregards

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#132]
From @handrews feedback [review](https://github.com/OAI/sig-workflows/issues/49#issuecomment-1836661780):

The Reference Object value is defined as:
> A value by default SHOULD override that of the referenced component. If the referenced object-type does not have a value field, then it has no effect.

What are the circumstances under which this SHOULD could reasonably be disregarded? The current language effectively allows implementations to arbitrarily disregard value, which would lead to interoperability problems. And dilute what it means to comply with the spec.

**Comment by handrews** [comment]
I'm guessing from the title that you plan to upgrade this to a MUST, which would definitely solve my concern :-)
