### ISSUE TITLE
Parameter target JSON Pointer

### ISSUE THREAD

**Issue by gcatanese** [OAI/sig-workflows#139]
The [Parameter Object](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#parameter-object) is supposed to be a valid JSON Pointer. 

In the Pet Coupons [example](https://github.com/OAI/sig-workflows/blob/e021569488ee7109e4dc1b272f9d204b932e238e/examples/1.0.0/pet-coupons.workflow.yaml#L119) the `target` is defined as `$request.body#/petId`, which is not a valid JSON Pointer.

In the FAPI-PAR [example](https://github.com/OAI/sig-workflows/blob/e021569488ee7109e4dc1b272f9d204b932e238e/examples/1.0.0/FAPI-PAR.workflow.yaml#L153) the `target` is defined as `/grant_type`, which is a valid JSON Pointer.

I guess the notation `$request.body#/json/pointer` makes clear where the target applies and it is flexible (other target options eventually?). Is it then better to clarify the usage of `target` in the Parameter Object? Or decide to apply a formal JSON Pointer implementation, therefore updating the examples?

**Comment by handrews** [comment]
The current wording for `target` includes:

> Useful for targeting specific request body parts

It sounds like that ought to be strengthened to say that JSON Pointers MUST be resolved against the request body.  Or it should allow full runtime expressions if there are other valid locations.

**Comment by gcatanese** [comment]
Indeed. It would be great to avoid any ambiguity. 

**Option 1**
The `target` attribute is a valid JSON Pointer (i.e. `/status`) resolved to the request body. In this case, it MUST be specified when `in` is defined as`body`.

**Options 2**
The `target` attribute is an expression (i.e. `$request.body#/status`) resolving to the request body, or other valid location.

Option 2 gives more flexibility, while option 1 gives clear guidance (that suits tooling better).

**Comment by ndenny** [comment]
Yeah, I think we have to go for Option 1. Option 2 may have just been an old idea we missed when updating the examples. I'll prep a quick PR to make it match for now.

**Comment by ndenny** [comment]
Gave it a go in #143

**Comment by frankkilcommins** [comment]
The intention here is indeed to use JSON Pointers to be resolved against the request body. As of now, I don't see a use case for targeting other locations. Thus we can improve the verbiage a little.

@gcatanese note that target is not required when `in` is specified as `body`. There are cases where a full request body could be provide (e.g., no JSON Pointer required) as well as situations where the parameters can contain `x-www-form-urlencoded parameters` which also specify `in` as `body`

**Comment by gcatanese** [comment]
@frankkilcommins I see, thanks for clarifying
