### ISSUE TITLE
`dependsOn` clarification and parallel execution

### ISSUE THREAD

**Issue by RomanHotsiy** [OAI/sig-workflows#153]
We have a question about `dependsOn`?

Why is it required? In the description it says it's to **ensure steps are "not processed in parallel"** BUT `steps` are defined as **An ordered list of steps**.

There is no mentions of parallel vs sequential execution.

Do we really need parallel execution complexity in the first version of the spec?
I'm worried that `dependsOn` may add too much friction for the workflow author.

**Comment by microapiframework** [comment]
I am not sure now, but we originally had intentions of supporting AsyncAPI as well. So it may have been introduced then to ensure steps were sequential instead of parallel. @frankkilcommins  or @ndenny or @shaisachs  do you guys recall?

**Comment by kevinduffey** [comment]
I am not sure now, but we originally had intentions of supporting AsyncAPI as well. So it may have been introduced then to ensure steps were sequential instead of parallel. @frankkilcommins or @ndenny or @shaisachs do you guys recall?

**Comment by kevinduffey** [comment]
I'd also add.. again this is trying to recall the conversation(s) around this some time back, that in the even we support AsyncAPI, in the case a given step needs some async steps to be completed before the step can proceed, this is how you would indicate steps (async or sync) must be completed before it could exectue.

**Comment by RomanHotsiy** [comment]
Should we add some note about it in the spec or maybe remove until it is clarified? This is a bit ambiguous for us as implementers.

**Comment by frankkilcommins** [comment]
I'm all for adding more clarity with in relation to the expected usage in the initial spec version. Parallel execution and AsyncAPI were in scope at one stage and `dependsOn` is related (but not solely) to those topics.

As it stands, it's there as an optional mechanism to add more explicit dependencies for steps should that be needed. One can imagine a workflow that grows in it's number of steps overtime, and such a workflow may have certain branching constructs specified via `onSuccess` (or `onFailure`). If an Success Action Object (`type: goto`) was defined, then potentially ensuring that all prerequisite needed by the reference steps are executed can give additional assurance to the ability to achieve the execution rather than responsibility on the referencing step.

That all being said, I'm not completely against removing it until we discover otherwise (and follow the YAGNI principle).

**Comment by kevinduffey** [comment]
So after today's meeting with Frank and Nick, we discussed this a little bit. I am going to throw out what I think might be a better (or perhaps in conjunction with the present spec) option for dependsOn. From a tooling perspective, Frank pointed out a couple of things but one in particular that caught my ear/concern is the ability to dependOn a step from another workflow, that could dependOn another step in another workflow, that depends on the original workflow.. thus making a circular reference. While detectable in say a validation tool, I feel like that could result in some messy difficult to follow workflows. Thus, I think, at least until we figure out how we will support async steps and workflows, we would benefit from adding the dependsOn to the Workflow scope, and possibly removing/shelving (for now) the step dependsOn. 
The concern I now have (and thank you Roman for bringing this up though for a different reason) is the per step dependsOn is perhaps not clear on how it will work. For example, if a workflow with 10 steps, at step 3 has a dependsOn and that is a step in a different workflow.. say step 5 in that workflow.. it's odd to me how you enforce/validate/execute that dependsOn in the other workflow. Is it JUST the one step that the dependsOn gets executed.. but it would in turn requre the steps before it most likely (but not for sure). Do we add documentation that indicates a dependsOn at the step level MUST be either the first or last step in that workflow? Per Frank's suggestion, having depedsOn ADD the ability to depend on a workflowId. But I will still argue that I don't quite see the benefit of a per step dependsOn vs a workflow scoped dependsOn. 
Frank also brought up (which led to my reasoning that a workflow scoped dependsOn makes more sense and removing step dependOn makes sense) in the example situation where you have a workflow that is for authorization. So you got this token based workflow. Now, every OTHER workflow (in the same and possibly other workflow documents) could just have step 1 of each workflow indicate they depend on the authorization workflow to ensure the subsequent steps can be assured of a token that can then be passed in as a header. This means every workflow has to manually add step JUST to depend on the workflow for authorization. That seems silly to me vs a workflows coped DependsOn. 

Until we discuss a bit more about how async may fit in to this, I am not convinced the complete removal of per step dependsOn is the right move. But as of now I feel like it makes more sense to not have it there, and have the workflow scoped dependsOn with a rule that all workflowId dependencies MUST have been executed (and ideally with success results at the end) before the given workflow can execute. I was talking to Nick in terms of say, code generation, I could see each workflow becoming a "wrapper" function around the steps of the workflow (which would in turn be individual request/response functions). So a depdnsOn could simply generate a call to another workflow "wrapper" function before any of the steps of that workflow are executed.. with some level of "if workflow1().result() == success { do my workflow steps }" sort of logic.

**Comment by frankkilcommins** [comment]
In the interest of moving the bike shedding off the critical path, I’m going to suggest the following:
-	We omit `dependsOn` from v1.0.0
-	We create an enhancement issue for parallelism with `dependsOn` (both at a workflow and step level)
-	We create a related enhancement issue for OAS related webhooks and callbacks with `dependsOn` behaviour

The main reasons for this:
- Time – We all want to get v1.0.0 out to the industry and the _optional_ `dependsOn` causes complexity with regards to mapping out dependency graphs to prevent circular references and other poorly configured workflows. This will slow vendor implementations.
- Limited functional gap – as we do not advertise or proclaim parallel step execution capabilities in `1.0.0` the majority of functionality can be managed with thoughtful sequential step authoring and being mindful of branching considerations
- Enhance a more vibrate community following a hopefully successful `1.0.0` rollout and learn from the application of the specification in the wild where `dependsOn` is an in-demand ask.
- Examples: To date we have not defined examples showcasing the appropriate use of `dependsOn`

**Comment by kevinduffey** [comment]
Agreed on all accounts. If I had one partial disagreement it would be to put dependsOn at workflow scope as that is not too difficult, but I agree, we want to get this out, so I'd lean towards removing it altogether and focus on that after 1.0.0.
