### ISSUE TITLE
Potential bug in the `pet-coupons.workflow.yaml` example

### ISSUE THREAD

**Issue by RomanHotsiy** [OAI/sig-workflows#154]
This looks like a bug in the example:

https://github.com/OAI/sig-workflows/blob/9164da1e3e63df94737d84bac4b135e2479688a8/examples/1.0.0/pet-coupons.workflow.yaml#L162-L170

I believe it can't have `type` and `format ` fields and instead it should have `name`, `value` and`in` fields.

**Comment by RomanHotsiy** [comment]
Please, confirm and I can open a PR.

**Comment by frankkilcommins** [comment]
@RomanHotsiy correct, `type` and `format` should not be specified within the workflow. These can be describe within the target OAS parameter schema definition
