### ISSUE TITLE
Revisit JSON Path examples

### ISSUE THREAD

**Issue by SensibleWood** [OAI/sig-workflows#160]
There are two JSON Path examples that have been discussed on Slack, namely:

https://github.com/OAI/sig-workflows/blob/1e74716b3c137765f1c8b987ef547dd36981c0a0/versions/1.0.0.md?plain=1#L486

and

https://github.com/OAI/sig-workflows/blob/1e74716b3c137765f1c8b987ef547dd36981c0a0/versions/1.0.0.md?plain=1#L692

neither of which look correct. The contention is that this is the right syntax if `pets` is an object:

`$.pets[?(@.length > 0)]`

And if `pets` is an array: 

`$.pets.*[?(@.length > 0)]`

And if you don't care whether its an object or an array:

`$.pets.[?(@.length > 0)]`

With all expressions either being truthy or returning no match.

The lines highlighted should be revisited, checked to see if they are correct, and then remedial action taken as required.

**Comment by frankkilcommins** [comment]
Agree these need to be revisited. The aim should be to conform to [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535.html). I'll try to carve out some time next week.

In both cases about, potentially the `count` function would be more suitable: `$[?count(@.pets) > 1]` depending on how the response schema is structured of course. Specifying a sample response JSON for which the conditions are applied would also be advisable.

A related topic, is what do we do if the response content type is `application/xml`. Do we need to consider that and possibly add XPath? This is related to the issue on enhancing the requestBody capabilities in #152

**Comment by SensibleWood** [comment]
Ok that makes sense now.  I had assumed that the original JSON Path spec was being implemented i.e. https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html when I read the Slack comments. The query expressions seem to the main difference to the original Gössner approach.

What's the tooling landscape like? Is there wide adoption for the latest version? To me there's an argument for supporting both versions, as support for the script expressions above is very common.

Regards the point about `application/xml` I think there is a strong argument for including XPath.  It'll make life much easier for implementers and consumers IMHO.

**Comment by frankkilcommins** [comment]
Notes from SIG meeting on March 13th

To move this forward, we propose the following:
- Amend the Criterion object `type` property to be either a `string` or an `Expression Type Object` (properties `name` and `type`)
- The supported string (short hand) types would be as currently described plus the addition of `XPath`. The default version of `XPath` would be [3.1](https://www.w3.org/TR/xpath-31) and the default for `JSON Path` would be [RFC 9535](https://www.rfc-editor.org/rfc/rfc9535.html).
- The `Expression Type Object` allows an author to deviate to a specific version (better suited to their tooling eco system)

```
- name: JSONPath
  version: draft-goessner-dispatch-jsonpath-00
```

```
- name: XPath
  version: xpath-30
```

The allowed `version` values will be enumerated for JSONPath and XPath
