### ISSUE TITLE
Review the 1.0.0 Draft Proposal

### ISSUE THREAD

**Issue by namdeirf** [OAI/sig-workflows#21]
SIG members are invited to review the initial draft proposal, which can be found [here](https://github.com/OAI/sig-workflows/blob/draft-version/versions/1.0.0.md).

**Comment by Macke** [comment]
suggest the following for Workflows specification...  happy to put it into a PR once there has been an initial discussion


## Introduction

The [OpenAPI Specification (OAS)](https://github.com/OAI/OpenAPI-Specification) defines a standard, programming language-agnostic interface description for HTTP APIs.  The complementary "Workflows specification" extends the OAS by defining a standard, programming language-agnostic interface description for a sequence of calls required to achieve a defined outcome in a particular use case. This will allow both humans and computers to discover and understand the steps required without access to source code, other documentation, or through network traffic inspection.

When properly defined, a consumer can understand and interact with the remote service comprising multiple steps with a minimal amount of implementation logic.

A Workflows definition can then be used by documentation generation tools to display the steps, enable code generation tools to generate servers and clients in various programming languages, testing tools, and many other use cases.

**Comment by frankkilcommins** [comment]
Draft spec has been reviewed and enhanced by the SIG members. It's now under broader discussion with the OAI TDC.

**Useful Info:**
[Spec](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md)
[Presentation deck for TDC](https://docs.google.com/presentation/d/1rua_le-UY0oruzlHlgWYF9AcMM2vR7jrjomlQMryq6E/edit?usp=sharing)
