### ISSUE TITLE
Agenda for September 28th, 2022

### ISSUE THREAD

**Issue by ndenny** [OAI/sig-workflows#26]
Remembering what we do

**Comment by davidapimetrics** [comment]
Minutes of Meeting:
Attending:
David O'Neill
Nick Denny
Andrew Brown
Stu Waldron
Frank Kilcommins
Shai Sachs

1) initial review of where we were up to after summer recess

2) housekeeping discussion - David O'Neill will be stepping back as champion with Andrew Brown stepping up
- ACTION: Frank to onboard Andrew + Shai with access to the services they need

3) Next steps agreed:
a) Meeting October 12 to be for a review of the current spec and identify gaps and holes and assign actions for filling them - FK to undertake some housekeeping on TBD items and other gaps
b) Post review - goal to define some sample YAML of it's use - DON will interact with openID connect providers for example 
c) Feedback to go into spec
d) take spec at that point to TSC for review

4) there being no other items, the meeting was adjourned.
