### ISSUE TITLE
Meeting: February 1, 2023

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#28]
Time: 17:00 GMT
Zoom Link: https://us02web.zoom.us/j/84963275150?pwd%3DOWM1T3B5aTdhKzI2WFVuSGJLTy9YQT09
Passcode: 870521

**Agenda**

- Review latest spec version changes outlined in last meeting actions
- Discuss slack topics/questions:
  - `onSuccess` expression logic
  - need for `required` steps

**Comment by frankkilcommins** [comment]
**Attendees**
- Frank Kilcommins
- Kevin Duffey
- Mark Haine
- David O'Neill
- Nick Denny
- Andrew Brown

**Minutes / Topics**
- Reviewed/Discussed a workflows example for a typical OAuth use-case. Frank explained the workflow referencing capability from a step and the example was updated for clarity
- Reviewed previous spec changes
- Discussed the next steps regarding taking the spec for broader review (OAI TSC and external friendlies - aka customers/companies where it's expected the benefits of the capabilities of the spec would fit well)

**Decisions**
- Rework the spec to reduce `Maps` in favour of lists (for `sources` and `workflows`)
- Do not address the challenge of access/authorization to workflow sources in this version of spec (see slack [thread](https://open-api.slack.com/archives/C022K8VD7AP/p1674864531372099) and Frank's proposals)
- Do not introduce _step required_ option into the spec. Instead prefer modular workflows and leverage the `step` ability to reference a workflow

**Actions**
- @frankkilcommins to update the draft specification to cover:
  - replacing `Maps` with lists for `sources` and `workflows`
  - introduce `Source Object` to describe a source and it's type
  - extend expression capabilities to handle referencing workflow outputs when referenced by a step
  - update examples as required
- @ndenny to share example worked on during call with @frankkilcommins  for inclusion and alignment with spec changes above
- @ndenny and David to discuss the spec with some additional contacts

**Comment by ndenny** [comment]
Added the sample code here: https://github.com/OAI/sig-workflows/tree/draft-version-minor-enrichment/examples/1.0.0

**Comment by frankkilcommins** [comment]
Spec update actions as mentioned in the issue are completed. I've bit the bullet and introduced a Parameter Object which is used by Steps to define a list of such parameters and enables describing the parameter locations which up until now were a little vague, open to clashes, and not supporting requests or form bodies. Now parameters can be mapped to the following locations:
- path
- query
- header
- query
- cookie
- request (or request location via JSON Pointer)
- workflow Input (for when a step references a standalone workflow)

**Comment by frankkilcommins** [comment]
> Added the sample code here: https://github.com/OAI/sig-workflows/tree/draft-version-minor-enrichment/examples/1.0.0

I've adjusted based on the latest spec changes
