### ISSUE TITLE
Add components section to improve reusability through referencing within the spec

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#43]
It's currently possible to compose a workflows document and reference other workflow documents, but referencing capabilities of steps and/or reusing step inputs across workflows or steps is limited.

The current scope and referencing of inputs and outputs for steps and workflows is described by the following picture:
![Workflows-Access-Scope-for-Inputs-and-Outputs](https://user-images.githubusercontent.com/15875424/231983697-766daad7-9345-419c-b915-46f569ea9fa2.png)

Defining workflow inputs, steps and/or step inputs under a global components section (similar to OpenAPI) could bring better reusability through referencing.

##### Components
Holds a set of reusable objects for different aspects of the Workflows Specification. All objects defined within the components object will have no effect on the workflow unless they are explicitly referenced from properties outside the components object.

| Field Name | Type | Description
|:-------------|:------:|-------------
| inputs | Map[`string`, [Schema Object]()] | An object to hold reusable JSON Schema objects to be referenced from workflow inputs. _Remark: possibly trimmed down version of OAS Schema Object_
| ~~steps~~ | ~~Map[`string`, [Step Object](https://mikeralphson.github.io/OpenAPI-Specification/workflows/1.0.0.html#step-object)]~~ | ~~An object to hold a reusable [Step Objects](https://mikeralphson.github.io/OpenAPI-Specification/workflows/1.0.0.html#step-object).~~
| parameters | Map[`string`, [Parameter Object](https://mikeralphson.github.io/OpenAPI-Specification/workflows/1.0.0.html#parameter-object)] | An object to hold reusable [Parameter Objects](https://mikeralphson.github.io/OpenAPI-Specification/workflows/1.0.0.html#parameter-object)

**Comment by MikeRalphson** [comment]
> possibly trimmed down version of OAS Schema Object

@frankkilcommins what would be the rationale for a cut-down schema object? We have got ourselves into a right state in OAS with subset-superset-sidesets before.

**Comment by shaisachs** [comment]
I added reference objects just now. Incorporating them into Steps and Parameters was no problem. However, because the `workflowInputs` is defined to be a `JSON Schema` object, it's a little more difficult - we need to embed reference objects inside that JSON Schema. Can we modify `workflowInputs` to something like an array of JSON Schema or reference object? Something like `[JSON Schema | Reference Object]`.

**Comment by MikeRalphson** [comment]
@shaisachs doesnt the schema object allow `$ref`s anyway?

**Comment by shaisachs** [comment]
I think so... But I guess we need to mention that in the system and provide some examples.
