### ISSUE TITLE
Request to be added as a contributor

### ISSUE THREAD

**Issue by LanreOyewole** [OAI/sig-workflows#75]
Hello all,
Following on from the details in the README.md page, I am raising this new issue, to request to be added as a contributor.

I have worked on message models, canonical schema, SOA architecture and API design for many years and have an interest in both sig-workflows and overlay-specification.  I have very good attention to detail, a knack for simplicity, and I am decent at documentation and communication.

Apologies if this is not the correct way to join, I might have misunderstood the README, if so, directions will be very much appreciated.

**Comment by frankkilcommins** [comment]
Hi @LanreOyewole,

Great that you are interested in participation.

It's open to join and get involved. The best way is to join the slack workspace and join in on the bi-weekly working group sessions. 

Info:
- Slack - if you have access to the OpenAPI slack workspace, then join the sig-workflows channel. If you do not have access, you're welcome to join by clicking [here](https://communityinviter.com/apps/open-api/openapi)
- Meetings - see [OAI calendar](https://www.openapis.org/calendar) and look for `OpenAPI Workflow SIG`. Alternatively, keep an eye on the meeting issues created in the repo.
