### ISSUE TITLE
Parameter Object Target Property: JSON Pointer + expression wording together is confusing

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#85]
The description is: A JSON Pointer expression identifying locations to inject the value. Can be useful for targeting specific request body part.

I haven't seen JSON Pointer + expression wording together before.

Even the rfc6901 doesn't refer to the JSON Pointer string as expression

**Comment by char0n** [comment]
Type definition for `target` fixed field was a bit confusing to me. The type is defined as `{JSON Pointer}` and not as `string`. I'd rather have `string` type there and be guided by field description what the string value represents.
